### Autograd: 자동 미분
- Tensor의 모든 연산에 대해 자동 미분을 제공
- 실행-기반-정의(define-by-run)프레임워크 - 코드를 어떻게 작성하여 실행하느냐에 따라 역전팍가 정의된다.

#### Variable
- tensor를 wrap하고 있음.
- tensor기반으로 정의된 대부분의 연산 지원
- 계산 완료 후 .backward() 메서드로 모든 gradient를 자동으로 계산
- .data 속성으로 raw tensor에도 접근 가능, 변화도는 .grad에 누적

#### Function
- Variable 과 Function은 상호 연결, 모든 연산과정 encoding & acyclic graph 생성
- Variable은 .grad_fn을 가짐 - Variable을 생성한 Function을 참조
- 도함수 계산을 위해서는 Variable의 .backward() 메서드 호출

In [1]:
import torch
from torch.autograd import Variable

In [13]:
x = Variable(torch.ones(2, 2), requires_grad = True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [14]:
y = x + 2
print(y)
print(y.grad_fn)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [15]:
z = y * y * 3
out = z.mean()

print(z, out)

(tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>), tensor(27., grad_fn=<MeanBackward1>))


In [16]:
out.backward()

In [17]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [28]:
x = torch.randn(3)
x = Variable(x, requires_grad=True)

y = x * 2
while y.data.norm() < 1000:
    y = y * 2

print(y)

tensor([-643.1922, 1392.8445, 1055.5046], grad_fn=<MulBackward>)
