### Pytorch tutorial
reference : https://9bow.github.io/PyTorch-tutorials-kr-0.3.1/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py


#### Tensor
텐서 생성 및 초기화
- torch.Tensor(shape) : 초기화되지 않은 텐서 생성
- torch.rand(shape) : 무작위로 초기화된 행렬 생성 (0~1사이의 수)
- torch.randn(shape) : 각원소가 정규분포를 따르도록 초기화된 행렬 생성
- .size() : 행렬의 크기 구하기

In [1]:
import torch

In [5]:
x = torch.Tensor(5, 3)
print(x)
print(x.size())

tensor([[ 0.0000e+00, -1.0842e-19,  0.0000e+00],
        [-1.0842e-19,  8.6667e-34,  1.4013e-45],
        [ 1.0401e-33,  1.4013e-45,  3.2218e-18],
        [ 1.5849e+29,  0.0000e+00,  0.0000e+00],
        [ 2.3983e-36,  1.4013e-45,  3.2217e-18]])
torch.Size([5, 3])


In [6]:
x = torch.rand(5,3)
print(x)
print(x.size())

tensor([[0.7880, 0.9478, 0.7735],
        [0.5129, 0.9058, 0.8656],
        [0.9605, 0.7123, 0.1502],
        [0.8434, 0.6744, 0.1274],
        [0.8650, 0.9792, 0.5090]])
torch.Size([5, 3])


#### Operation
- 덧셈:
    - x + y
    - torch.add(x, y)
    - target1.add_(target_2) : inplace 덧셈 x+y를 y에 대입

In [7]:
y = torch.rand(5,3)
print(x+y)

tensor([[1.3714, 1.4621, 1.6345],
        [0.9467, 0.9824, 1.0889],
        [1.1586, 1.4912, 0.7689],
        [1.7692, 1.3471, 0.3381],
        [0.9484, 1.5601, 1.2400]])


In [8]:
print(torch.add(x,y))

tensor([[1.3714, 1.4621, 1.6345],
        [0.9467, 0.9824, 1.0889],
        [1.1586, 1.4912, 0.7689],
        [1.7692, 1.3471, 0.3381],
        [0.9484, 1.5601, 1.2400]])


In [10]:
result = torch.Tensor(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[1.3714, 1.4621, 1.6345],
        [0.9467, 0.9824, 1.0889],
        [1.1586, 1.4912, 0.7689],
        [1.7692, 1.3471, 0.3381],
        [0.9484, 1.5601, 1.2400]])


In [12]:
y.add_(x)
print(y)

tensor([[2.1593, 2.4099, 2.4079],
        [1.4596, 1.8882, 1.9545],
        [2.1191, 2.2036, 0.9191],
        [2.6126, 2.0216, 0.4655],
        [1.8134, 2.5393, 1.7490]])


#### indexing
- numpy 의 인덱싱 표현법 사용가능

In [16]:
print(x[1])
print(x[:,2])
print(x[1,2])

tensor([0.5129, 0.9058, 0.8656])
tensor([0.7735, 0.8656, 0.1502, 0.1274, 0.5090])
tensor(0.8656)


#### 크기 변경
tensor의 크기(size)나 모양(shape) 변경
- torch.view()

In [18]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1, 8)
print(x.size(), y.size(), z.size())

(torch.Size([4, 4]), torch.Size([16]), torch.Size([2, 8]))


#### NumPy 변환
- .numpy(): numpy 배열로 변환하여 리턴
- torch tensor와 numpy 배열은 저장 공간을 공유하기 때문에, 하나를 변경하면 다른 하나도 변경

In [21]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [22]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [23]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


#### NumPy 배열을 Torch Tensor로 변환
- torch.from_numpy(numpy_array)

In [24]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


#### CUDA Tensors
- .cuda 메소드로 tensor를 gpu상으로 옮길 수 있음

In [25]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y